// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crowdfund/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetCampaignsRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCampaignsRequest) Reset()         { *m = QueryGetCampaignsRequest{} }
func (m *QueryGetCampaignsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCampaignsRequest) ProtoMessage()    {}
func (*QueryGetCampaignsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{2}
}
func (m *QueryGetCampaignsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCampaignsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCampaignsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCampaignsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCampaignsRequest.Merge(m, src)
}
func (m *QueryGetCampaignsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCampaignsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCampaignsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCampaignsRequest proto.InternalMessageInfo

func (m *QueryGetCampaignsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetCampaignsResponse struct {
	Campaigns Campaigns `protobuf:"bytes,1,opt,name=Campaigns,proto3" json:"Campaigns"`
}

func (m *QueryGetCampaignsResponse) Reset()         { *m = QueryGetCampaignsResponse{} }
func (m *QueryGetCampaignsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCampaignsResponse) ProtoMessage()    {}
func (*QueryGetCampaignsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{3}
}
func (m *QueryGetCampaignsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCampaignsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCampaignsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCampaignsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCampaignsResponse.Merge(m, src)
}
func (m *QueryGetCampaignsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCampaignsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCampaignsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCampaignsResponse proto.InternalMessageInfo

func (m *QueryGetCampaignsResponse) GetCampaigns() Campaigns {
	if m != nil {
		return m.Campaigns
	}
	return Campaigns{}
}

type QueryAllCampaignsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCampaignsRequest) Reset()         { *m = QueryAllCampaignsRequest{} }
func (m *QueryAllCampaignsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCampaignsRequest) ProtoMessage()    {}
func (*QueryAllCampaignsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{4}
}
func (m *QueryAllCampaignsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCampaignsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCampaignsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCampaignsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCampaignsRequest.Merge(m, src)
}
func (m *QueryAllCampaignsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCampaignsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCampaignsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCampaignsRequest proto.InternalMessageInfo

func (m *QueryAllCampaignsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCampaignsResponse struct {
	Campaigns  []Campaigns         `protobuf:"bytes,1,rep,name=Campaigns,proto3" json:"Campaigns"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCampaignsResponse) Reset()         { *m = QueryAllCampaignsResponse{} }
func (m *QueryAllCampaignsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCampaignsResponse) ProtoMessage()    {}
func (*QueryAllCampaignsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{5}
}
func (m *QueryAllCampaignsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCampaignsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCampaignsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCampaignsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCampaignsResponse.Merge(m, src)
}
func (m *QueryAllCampaignsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCampaignsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCampaignsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCampaignsResponse proto.InternalMessageInfo

func (m *QueryAllCampaignsResponse) GetCampaigns() []Campaigns {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *QueryAllCampaignsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPledgesRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetPledgesRequest) Reset()         { *m = QueryGetPledgesRequest{} }
func (m *QueryGetPledgesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPledgesRequest) ProtoMessage()    {}
func (*QueryGetPledgesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{6}
}
func (m *QueryGetPledgesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPledgesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPledgesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPledgesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPledgesRequest.Merge(m, src)
}
func (m *QueryGetPledgesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPledgesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPledgesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPledgesRequest proto.InternalMessageInfo

func (m *QueryGetPledgesRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetPledgesResponse struct {
	Pledges Pledges `protobuf:"bytes,1,opt,name=Pledges,proto3" json:"Pledges"`
}

func (m *QueryGetPledgesResponse) Reset()         { *m = QueryGetPledgesResponse{} }
func (m *QueryGetPledgesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPledgesResponse) ProtoMessage()    {}
func (*QueryGetPledgesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{7}
}
func (m *QueryGetPledgesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPledgesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPledgesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPledgesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPledgesResponse.Merge(m, src)
}
func (m *QueryGetPledgesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPledgesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPledgesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPledgesResponse proto.InternalMessageInfo

func (m *QueryGetPledgesResponse) GetPledges() Pledges {
	if m != nil {
		return m.Pledges
	}
	return Pledges{}
}

type QueryAllPledgesRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPledgesRequest) Reset()         { *m = QueryAllPledgesRequest{} }
func (m *QueryAllPledgesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPledgesRequest) ProtoMessage()    {}
func (*QueryAllPledgesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{8}
}
func (m *QueryAllPledgesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPledgesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPledgesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPledgesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPledgesRequest.Merge(m, src)
}
func (m *QueryAllPledgesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPledgesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPledgesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPledgesRequest proto.InternalMessageInfo

func (m *QueryAllPledgesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPledgesResponse struct {
	Pledges    []Pledges           `protobuf:"bytes,1,rep,name=Pledges,proto3" json:"Pledges"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPledgesResponse) Reset()         { *m = QueryAllPledgesResponse{} }
func (m *QueryAllPledgesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPledgesResponse) ProtoMessage()    {}
func (*QueryAllPledgesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{9}
}
func (m *QueryAllPledgesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPledgesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPledgesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPledgesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPledgesResponse.Merge(m, src)
}
func (m *QueryAllPledgesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPledgesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPledgesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPledgesResponse proto.InternalMessageInfo

func (m *QueryAllPledgesResponse) GetPledges() []Pledges {
	if m != nil {
		return m.Pledges
	}
	return nil
}

func (m *QueryAllPledgesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "youngestdev.crowdfund.crowdfund.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "youngestdev.crowdfund.crowdfund.QueryParamsResponse")
	proto.RegisterType((*QueryGetCampaignsRequest)(nil), "youngestdev.crowdfund.crowdfund.QueryGetCampaignsRequest")
	proto.RegisterType((*QueryGetCampaignsResponse)(nil), "youngestdev.crowdfund.crowdfund.QueryGetCampaignsResponse")
	proto.RegisterType((*QueryAllCampaignsRequest)(nil), "youngestdev.crowdfund.crowdfund.QueryAllCampaignsRequest")
	proto.RegisterType((*QueryAllCampaignsResponse)(nil), "youngestdev.crowdfund.crowdfund.QueryAllCampaignsResponse")
	proto.RegisterType((*QueryGetPledgesRequest)(nil), "youngestdev.crowdfund.crowdfund.QueryGetPledgesRequest")
	proto.RegisterType((*QueryGetPledgesResponse)(nil), "youngestdev.crowdfund.crowdfund.QueryGetPledgesResponse")
	proto.RegisterType((*QueryAllPledgesRequest)(nil), "youngestdev.crowdfund.crowdfund.QueryAllPledgesRequest")
	proto.RegisterType((*QueryAllPledgesResponse)(nil), "youngestdev.crowdfund.crowdfund.QueryAllPledgesResponse")
}

func init() { proto.RegisterFile("crowdfund/query.proto", fileDescriptor_d40d9c8bf30e3a39) }

var fileDescriptor_d40d9c8bf30e3a39 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb3, 0x69, 0x49, 0xc5, 0x82, 0x38, 0x2c, 0xa5, 0x1f, 0x11, 0x72, 0x91, 0x0f, 0x34,
	0x44, 0xe0, 0x25, 0x29, 0x28, 0xc0, 0x2d, 0x45, 0x50, 0x0e, 0x08, 0x85, 0x1c, 0x11, 0x07, 0x36,
	0xf1, 0xb2, 0x58, 0x38, 0x5e, 0x37, 0x76, 0x0a, 0x11, 0xe2, 0xc2, 0x13, 0x20, 0x78, 0x05, 0x8e,
	0x5c, 0x10, 0x5c, 0x10, 0x2f, 0xd0, 0x63, 0x25, 0x2e, 0x9c, 0x10, 0x4a, 0x78, 0x90, 0x2a, 0xbb,
	0x13, 0xc7, 0x69, 0x5c, 0xd9, 0xfd, 0xb8, 0x59, 0x9b, 0xf9, 0xcf, 0xfc, 0xfe, 0x3b, 0xb3, 0x13,
	0x7c, 0xa9, 0xdd, 0x95, 0x6f, 0xec, 0x97, 0x3d, 0xcf, 0xa6, 0xdb, 0x3d, 0xde, 0xed, 0x5b, 0x7e,
	0x57, 0x86, 0x92, 0xac, 0xf5, 0x65, 0xcf, 0x13, 0x3c, 0x08, 0x6d, 0xbe, 0x63, 0x45, 0x21, 0x93,
	0xaf, 0xe2, 0xa2, 0x90, 0x42, 0xaa, 0x58, 0x3a, 0xfa, 0xd2, 0xb2, 0xe2, 0x65, 0x21, 0xa5, 0x70,
	0x39, 0x65, 0xbe, 0x43, 0x99, 0xe7, 0xc9, 0x90, 0x85, 0x8e, 0xf4, 0x02, 0xf8, 0xb5, 0xdc, 0x96,
	0x41, 0x47, 0x06, 0xb4, 0xc5, 0x02, 0xae, 0xab, 0xd1, 0x9d, 0x4a, 0x8b, 0x87, 0xac, 0x42, 0x7d,
	0x26, 0x1c, 0x4f, 0x05, 0x43, 0xec, 0xd2, 0x84, 0xcb, 0x67, 0x5d, 0xd6, 0x19, 0xe7, 0x58, 0x9d,
	0x9c, 0xb7, 0x59, 0xc7, 0x67, 0x8e, 0x88, 0xd2, 0x2f, 0xc7, 0x24, 0x2e, 0xb7, 0x05, 0x87, 0x1f,
	0xcc, 0x45, 0x4c, 0x9e, 0x8e, 0xaa, 0x35, 0x54, 0xa2, 0x26, 0xdf, 0xee, 0xf1, 0x20, 0x34, 0x9f,
	0xe3, 0x8b, 0x53, 0xa7, 0x81, 0x2f, 0xbd, 0x80, 0x93, 0x07, 0xb8, 0xa0, 0x0b, 0xae, 0xa0, 0x2b,
	0xa8, 0x74, 0xae, 0xba, 0x6e, 0xa5, 0x5c, 0x85, 0xa5, 0x13, 0x6c, 0xce, 0xef, 0xfe, 0x5d, 0xcb,
	0x35, 0x41, 0x6c, 0x96, 0xf1, 0x8a, 0xca, 0xbe, 0xc5, 0xc3, 0xfb, 0x63, 0x4e, 0xa8, 0x4c, 0x2e,
	0xe0, 0xbc, 0x63, 0xab, 0xf4, 0xf3, 0xcd, 0xbc, 0x63, 0x9b, 0xaf, 0xf1, 0x6a, 0x42, 0x2c, 0xf0,
	0x3c, 0xc1, 0x67, 0xa3, 0x43, 0x40, 0x2a, 0xa7, 0x22, 0x45, 0x0a, 0xa0, 0x9a, 0xa4, 0x30, 0x5b,
	0x00, 0x56, 0x77, 0xdd, 0x19, 0xb0, 0x87, 0x18, 0x4f, 0x1a, 0x01, 0xc5, 0xae, 0x5a, 0xba, 0x6b,
	0xd6, 0xa8, 0x6b, 0x96, 0x9e, 0x11, 0xe8, 0x9a, 0xd5, 0x60, 0x82, 0x83, 0xb6, 0x19, 0x53, 0x9a,
	0x3f, 0x10, 0x38, 0x9a, 0x2e, 0x92, 0xec, 0x68, 0xee, 0x84, 0x8e, 0xc8, 0xd6, 0x14, 0x75, 0x1e,
	0xba, 0x96, 0x46, 0xad, 0x61, 0xa6, 0xb0, 0x4b, 0x78, 0x69, 0xdc, 0x87, 0x86, 0x1e, 0xa0, 0xc3,
	0x3a, 0xd6, 0xc6, 0xcb, 0x33, 0x91, 0xe0, 0xee, 0x11, 0x5e, 0x80, 0x23, 0xb8, 0xc0, 0x52, 0xfa,
	0x00, 0xe9, 0x78, 0x70, 0x36, 0x96, 0x9b, 0x2f, 0x00, 0xa7, 0xee, 0xba, 0x07, 0x70, 0x4e, 0xab,
	0x4f, 0x5f, 0x11, 0xf8, 0x88, 0x97, 0x48, 0xf2, 0x31, 0x77, 0x02, 0x1f, 0xa7, 0xd6, 0x9f, 0xea,
	0xa7, 0x05, 0x7c, 0x46, 0xe1, 0x92, 0x2f, 0x08, 0x17, 0xf4, 0xb3, 0x23, 0x1b, 0xa9, 0x58, 0xb3,
	0x6f, 0xbf, 0x78, 0xeb, 0x68, 0x22, 0xcd, 0x62, 0xd2, 0x0f, 0xbf, 0xff, 0x7f, 0xce, 0x5f, 0x23,
	0xeb, 0x34, 0xa6, 0xa6, 0xb1, 0x85, 0x74, 0x60, 0x65, 0x91, 0x5f, 0x28, 0x36, 0xea, 0xe4, 0x6e,
	0xb6, 0xa2, 0x09, 0x1b, 0xa3, 0x78, 0xef, 0x38, 0x52, 0xa0, 0xae, 0x29, 0xea, 0x0a, 0xa1, 0xa9,
	0xd4, 0xd1, 0x42, 0xa5, 0xef, 0x1c, 0xfb, 0x3d, 0xf9, 0x89, 0xf0, 0xf9, 0x28, 0x5d, 0xdd, 0x75,
	0xb3, 0x1a, 0x48, 0xd8, 0x2c, 0x59, 0x0d, 0x24, 0xed, 0x0b, 0xb3, 0xaa, 0x0c, 0x5c, 0x27, 0xe5,
	0xec, 0x06, 0xc8, 0x77, 0x14, 0x8d, 0x2f, 0xa9, 0x65, 0xbe, 0xbc, 0xe9, 0x67, 0x56, 0xbc, 0x73,
	0x74, 0x21, 0x20, 0xdf, 0x56, 0xc8, 0x94, 0xdc, 0x48, 0x9f, 0x14, 0xad, 0xd4, 0x37, 0xfe, 0x0d,
	0x61, 0x0c, 0xa9, 0x46, 0xf7, 0x5d, 0xcb, 0x7c, 0x69, 0xc7, 0x03, 0x9f, 0x7d, 0xf5, 0xe6, 0x4d,
	0x05, 0x5e, 0x26, 0xa5, 0xac, 0xe0, 0x9b, 0x8f, 0x77, 0x07, 0x06, 0xda, 0x1b, 0x18, 0xe8, 0xdf,
	0xc0, 0x40, 0x1f, 0x87, 0x46, 0x6e, 0x6f, 0x68, 0xe4, 0xfe, 0x0c, 0x8d, 0xdc, 0xb3, 0xaa, 0x70,
	0xc2, 0x57, 0xbd, 0x96, 0xd5, 0x96, 0x9d, 0x43, 0xb2, 0xbd, 0x8d, 0x7d, 0x87, 0x7d, 0x9f, 0x07,
	0xad, 0x82, 0xfa, 0xc7, 0xde, 0xd8, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x89, 0x52, 0x77, 0x27, 0x97,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Campaigns by id.
	Campaigns(ctx context.Context, in *QueryGetCampaignsRequest, opts ...grpc.CallOption) (*QueryGetCampaignsResponse, error)
	// Queries a list of Campaigns items.
	CampaignsAll(ctx context.Context, in *QueryAllCampaignsRequest, opts ...grpc.CallOption) (*QueryAllCampaignsResponse, error)
	// Queries a Pledges by id.
	Pledges(ctx context.Context, in *QueryGetPledgesRequest, opts ...grpc.CallOption) (*QueryGetPledgesResponse, error)
	// Queries a list of Pledges items.
	PledgesAll(ctx context.Context, in *QueryAllPledgesRequest, opts ...grpc.CallOption) (*QueryAllPledgesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/youngestdev.crowdfund.crowdfund.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Campaigns(ctx context.Context, in *QueryGetCampaignsRequest, opts ...grpc.CallOption) (*QueryGetCampaignsResponse, error) {
	out := new(QueryGetCampaignsResponse)
	err := c.cc.Invoke(ctx, "/youngestdev.crowdfund.crowdfund.Query/Campaigns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CampaignsAll(ctx context.Context, in *QueryAllCampaignsRequest, opts ...grpc.CallOption) (*QueryAllCampaignsResponse, error) {
	out := new(QueryAllCampaignsResponse)
	err := c.cc.Invoke(ctx, "/youngestdev.crowdfund.crowdfund.Query/CampaignsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Pledges(ctx context.Context, in *QueryGetPledgesRequest, opts ...grpc.CallOption) (*QueryGetPledgesResponse, error) {
	out := new(QueryGetPledgesResponse)
	err := c.cc.Invoke(ctx, "/youngestdev.crowdfund.crowdfund.Query/Pledges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PledgesAll(ctx context.Context, in *QueryAllPledgesRequest, opts ...grpc.CallOption) (*QueryAllPledgesResponse, error) {
	out := new(QueryAllPledgesResponse)
	err := c.cc.Invoke(ctx, "/youngestdev.crowdfund.crowdfund.Query/PledgesAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Campaigns by id.
	Campaigns(context.Context, *QueryGetCampaignsRequest) (*QueryGetCampaignsResponse, error)
	// Queries a list of Campaigns items.
	CampaignsAll(context.Context, *QueryAllCampaignsRequest) (*QueryAllCampaignsResponse, error)
	// Queries a Pledges by id.
	Pledges(context.Context, *QueryGetPledgesRequest) (*QueryGetPledgesResponse, error)
	// Queries a list of Pledges items.
	PledgesAll(context.Context, *QueryAllPledgesRequest) (*QueryAllPledgesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Campaigns(ctx context.Context, req *QueryGetCampaignsRequest) (*QueryGetCampaignsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Campaigns not implemented")
}
func (*UnimplementedQueryServer) CampaignsAll(ctx context.Context, req *QueryAllCampaignsRequest) (*QueryAllCampaignsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CampaignsAll not implemented")
}
func (*UnimplementedQueryServer) Pledges(ctx context.Context, req *QueryGetPledgesRequest) (*QueryGetPledgesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pledges not implemented")
}
func (*UnimplementedQueryServer) PledgesAll(ctx context.Context, req *QueryAllPledgesRequest) (*QueryAllPledgesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PledgesAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/youngestdev.crowdfund.crowdfund.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Campaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Campaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/youngestdev.crowdfund.crowdfund.Query/Campaigns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Campaigns(ctx, req.(*QueryGetCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CampaignsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CampaignsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/youngestdev.crowdfund.crowdfund.Query/CampaignsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CampaignsAll(ctx, req.(*QueryAllCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Pledges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPledgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Pledges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/youngestdev.crowdfund.crowdfund.Query/Pledges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Pledges(ctx, req.(*QueryGetPledgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PledgesAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPledgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PledgesAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/youngestdev.crowdfund.crowdfund.Query/PledgesAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PledgesAll(ctx, req.(*QueryAllPledgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "youngestdev.crowdfund.crowdfund.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Campaigns",
			Handler:    _Query_Campaigns_Handler,
		},
		{
			MethodName: "CampaignsAll",
			Handler:    _Query_CampaignsAll_Handler,
		},
		{
			MethodName: "Pledges",
			Handler:    _Query_Pledges_Handler,
		},
		{
			MethodName: "PledgesAll",
			Handler:    _Query_PledgesAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crowdfund/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetCampaignsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCampaignsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCampaignsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCampaignsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCampaignsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCampaignsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Campaigns.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCampaignsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCampaignsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCampaignsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCampaignsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCampaignsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCampaignsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Campaigns) > 0 {
		for iNdEx := len(m.Campaigns) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Campaigns[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPledgesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPledgesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPledgesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPledgesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPledgesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPledgesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Pledges.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPledgesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPledgesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPledgesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPledgesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPledgesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPledgesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Pledges) > 0 {
		for iNdEx := len(m.Pledges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pledges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetCampaignsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetCampaignsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Campaigns.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCampaignsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCampaignsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Campaigns) > 0 {
		for _, e := range m.Campaigns {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPledgesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetPledgesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Pledges.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPledgesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPledgesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Pledges) > 0 {
		for _, e := range m.Pledges {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCampaignsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCampaignsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCampaignsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCampaignsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCampaignsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCampaignsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Campaigns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Campaigns.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCampaignsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCampaignsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCampaignsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCampaignsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCampaignsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCampaignsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Campaigns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Campaigns = append(m.Campaigns, Campaigns{})
			if err := m.Campaigns[len(m.Campaigns)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPledgesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPledgesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPledgesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPledgesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPledgesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPledgesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pledges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Pledges.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPledgesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPledgesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPledgesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPledgesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPledgesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPledgesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pledges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pledges = append(m.Pledges, Pledges{})
			if err := m.Pledges[len(m.Pledges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
